insert into unit_of_measure (description) values ( 'Teaspoon' );
insert into unit_of_measure (description) values ( 'Tablespoon' );
insert into unit_of_measure (description) values ( 'Cup' );
insert into unit_of_measure (description) values ( 'Pinch' );
insert into unit_of_measure (description) values ( 'Ounce' );
insert into unit_of_measure (description) values ( 'Ripe' );
INSERT INTO category (category_name) VALUES ('American');
INSERT INTO category (category_name) VALUES ('Italian');
INSERT INTO category (category_name) VALUES ('Mexican');
INSERT INTO category (category_name) VALUES ('Fast Food');
